In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
import os
print (os.getcwd()) #현재 디렉토리의

C:\Users\adboy\Desktop\study\python\jupyter\boaz\H1B_Visa_prediction_kaggle

In [4]:
file_path='./datas/'
file_name=file_path+'h1b_train.csv'
train=pd.read_csv(file_name)
train=train.loc[(train['CASE_STATUS']=='CERTIFIED') | (train['CASE_STATUS']=='DENIED')]

In [5]:
train

,Unnamed: 0,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
0,1349742,CERTIFIED,"INTERNATIONAL SYSTEMS TECHNOLOGIES, INC.",Computer Programmers,PROGRAMMER ANALYST,Y,61589.0,2014.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
1,789205,CERTIFIED,GOOGLE INC.,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,SITE RELIABILITY ENGINEER,Y,79144.0,2015.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
2,1617140,CERTIFIED,WIPRO LIMITED,"Computer Occupations, All Other",PROJECT MANAGER,Y,73882.0,2014.0,"EL SEGUNDO, CALIFORNIA",-118.416465,33.919180
3,2757905,CERTIFIED,"CPO SERVICES, INC.",Orthotists and Prosthetists,STAFF PROSTHETIST,Y,61589.0,2011.0,"PEORIA, ILLINOIS",-89.588986,40.693649
5,693102,DENIED,"UNIVERSITY OF CALIFORNIA, SAN DIEGO","MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",ASSISTANT PROJECT SCIENTIST,Y,42120.0,2015.0,"LA JOLLA, CALIFORNIA",-117.271272,32.832811
6,2662510,CERTIFIED,GOOGLE INC.,"Computer Software Engineers, Applications",SOFTWARE ENGINEER,Y,82035.0,2011.0,"MOUNTAIN VIEW, CALIFORNIA",-122.083851,37.386052
7,636434,CERTIFIED,"COMPREHAB, INC.",PHYSICAL THERAPISTS,PHYSICAL THERAPIST,N,64168.0,2016.0,"GASTONIA, NORTH CAROLINA",-81.187301,35.262082
8,2265757,CERTIFIED,JPMORGAN CHASE AND CO.,"Software Developers, Applications",APPLICATIONS DEVELOPER,Y,92726.0,2012.0,"COLUMBUS, OHIO",-82.998794,39.961176
9,2927315,CERTIFIED,"IRONBRIDGE CONSULTING, LLC","Information Security Analysts, Web Developers,...",SOFTWARE ENGINEER/ NETWORK ANALYST,Y,57866.0,2011.0,"ARLINGTON, VIRGINIA",-77.106770,38.879970
10,1696111,CERTIFIED,"AXON SOLUTIONS, INC.",Computer Systems Analysts,MANAGING CONSULTANT,Y,91998.0,2014.0,"UNIVERSAL CITY, CALIFORNIA",-118.350578,34.139769
11,2042418,CERTIFIED,MICROSOFT CORPORATION,"Software Developers, Applications",SOFTWARE DEVELOPMENT ENGINEER IN TEST,Y,86278.0,2013.0,"REDMOND, WASHINGTON",-122.121512,47.673988
12,2556938,CERTIFIED,MOBILE IRON INC.,"Software Developers, Systems Software",SYSTEMS ENGINEER,Y,103709.0,2012.0,"MOUNTAIN VIEW, CALIFORNIA",-122.083851,37.386052
13,1620167,CERTIFIED,"TECHNIP USA, INC.",Chemical Engineers,FACILITIES SPECIALIST,Y,75298.0,2014.0,"HOUSTON, TEXAS",-95.369803,29.760427
14,2066155,CERTIFIED,"COMMVAULT AMERICAS, INC.",Computer Systems Analysts,SYSTEM TESTER,Y,74651.0,2013.0,"OCEANPORT, NEW JERSEY",-74.015138,40.318166
15,2836033,CERTIFIED,CUMMINS INC.,Mechanical Engineers,SENIOR MECHANICAL ENGINEER - PERFORMANCE IMPRO...,Y,66019.0,2011.0,"FRIDLEY, MINNESOTA",-93.263282,45.086077
16,1649897,CERTIFIED,"PACIFIC INVESTMENT MANAGEMENT COMPANY, LLC","Securities, Commodities, and Financial Service...","VICE PRESIDENT, PORTFOLIO MANAGER",Y,57949.0,2014.0,"NEWPORT BEACH, CALIFORNIA",-117.928947,33.618910
17,734416,CERTIFIED,UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER AT S...,"HEALTH SPECIALTIES TEACHERS, POSTSECONDARY",ASSISTANT PROFESSOR,Y,96277.0,2015.0,"SAN ANTONIO, TEXAS",-98.493628,29.424122
18,2959714,CERTIFIED,"HARTE-HANKS DATA TECHNOLOGIES, INC.",Marketing Managers,ASSOCIATE PRODUCT MANAGER,Y,55931.0,2011.0,"LINTHICUM HEIGHTS, MARYLAND",-76.652746,39.205108
19,1498142,CERTIFIED,LENORA SYSTEMS INC,Computer Systems Analysts,PROGRAMMER ANALYST,Y,57075.0,2014.0,"DALLAS, TEXAS",-96.796988,32.776664
20,98397,CERTIFIED,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,TECHNOLOGY LEAD - US,Y,89149.0,2016.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
21,2196173,CERTIFIED,HITACHI CONSULTING CORPORATION,"Software Developers, Applications",SOFTWARE ENGINEER,Y,73174.0,2013.0,"REDMOND, WASHINGTON",-122.121512,47.673988
22,2511101,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,PROJECT LEAD,Y,76315.0,2012.0,"TAMPA, FLORIDA",-82.457178,27.950575
24,718222,CERTIFIED,"FORTINET, INC.","COMPUTER OCCUPATIONS, ALL OTHER",CARRIER READINESS TEST ENGINEER,Y,77563.0,2015.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
25,46751,CERTIFIED,"INDEED, INC.",MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,ONLINE MARKET ANALYST,N,60258.0,2016.0,"AUSTIN, TEXAS",-97.743061,30.267153
26,1961506,CERTIFIED,"CAZARCH, INC.",Architectural and Civil Drafters,ARCHITETURAL DESIGNER,Y,40685.0,2013.0,"BROOKLYN, NEW YORK",-73.944158,40.678178
27,1862817,CERTIFIED,CREDIT SUISSE SECURITIES (USA) LLC,Accountants and Auditors,EXEMPT NON-OFFICER,Y,55370.0,2013.0,"NEW YORK, NEW YORK",-74.005941,40.712784
28,2723040,CERTIFIED,"JCG TECHNOLOGIES, INC.",Computer Programmers,COMPUTER PROGRAMMER,Y,67995.0,2011.0,"WESTBOROUGH, MASSACHUSETTS",-71.616129,42.269522
29,913307,DENIED,APERI CORPORATION,COMPUTER HARDWARE ENGINEERS,SYSTEMS ENGINEER,Y,66200.0,2015.0,"CAMARILLO, CALIFORNIA",-119.037602,34.216394
30,2472137,CERTIFIED,"UPMC EMERGENCY MEDICINE, INC.","Physicians and Surgeons, All Other",HOSPITALIST,Y,81994.0,2012.0,"GREENVILLE, PENNSYLVANIA",-80.391179,41.404499
31,1773253,CERTIFIED,DELOITTE CONSULTING LLP,Computer Systems Analysts,CONSULTANT,Y,75899.0,2014.0,"BALA CYNWYD, PENNSYLVANIA",-75.230404,40.013142
...,...,...,...,...,...,...,...,...,...,...,...
1802423,1774076,CERTIFIED,ERNST & YOUNG U.S. LLP,Management Analysts,TAS SENIOR,Y,93538.0,2014.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
1802424,1687095,CERTIFIED,HYUNDAI DYMOS GEORGIA LLC,Financial Analysts,FINANCIAL SPECIALIST,Y,49088.0,2014.0,"WEST POINT, GEORGIA",-85.183275,32.877906
1802425,2408268,CERTIFIED,TRUSTEK INC.,Database Administrators,SQL SERVER DBA,Y,60154.0,2012.0,"SOUTH PLAINFIELD, NEW JERSEY",-74.411540,40.579270
1802426,1035749,CERTIFIED,TATA CONSULTANCY SERVICES LIMITED,COMPUTER SYSTEMS ANALYSTS,ANALYST,Y,41163.0,2015.0,"SAN JUAN, PUERTO RICO",-66.105735,18.465539
1802427,290670,CERTIFIED,MICROSOFT CORPORATION,"SOFTWARE DEVELOPERS, APPLICATIONS",SOFTWARE ENGINEER,Y,101088.0,2016.0,"REDMOND, WASHINGTON",-122.121512,47.673988
1802428,1601611,CERTIFIED,"TECH MAHINDRA ( AMERICAS), INC","Computer Occupations, All Other",SOFTWARE TEST ENGINEER,Y,77938.0,2014.0,"RICHARDSON, TEXAS",-96.729852,32.948334
1802429,2555937,CERTIFIED,RESOURCESOFT INC,Database Administrators,DATABASE ADMINISTRATOR,Y,53498.0,2012.0,"BOSTON, MASSACHUSETTS",-71.058880,42.360083
1802430,1559957,CERTIFIED,KANSAS STATE UNIVERSITY,"Biological Scientists, All Other",WEB/DATABASE DEVELOPER,Y,40706.0,2014.0,"MANHATTAN, KANSAS",-96.571669,39.183608
1802431,2812414,CERTIFIED,IREDELL-STATESVILLE SCHOOLS,"Middle School Teachers, Except Special and Voc...",ESL TEACHER,Y,37987.0,2011.0,"TROUTMAN, NORTH CAROLINA",NaN,NaN
1802433,757654,CERTIFIED,WIPRO LIMITED,"COMPUTER OCCUPATIONS, ALL OTHER",TEST ENGINEER LEVEL 1,Y,60528.0,2015.0,"PALO ALTO, CALIFORNIA",-122.143020,37.441883
1802435,1728823,CERTIFIED,WIPRO LIMITED,"Computer Occupations, All Other",LEAD ENGINEER,Y,62878.0,2014.0,"WILMINGTON, DELAWARE",-75.539788,39.739072
1802436,252105,CERTIFIED,SCINTILLA SOFT INC,COMPUTER PROGRAMMERS,PROGRAMMER ANALYST,N,54850.0,2016.0,"LOS ANGELES, CALIFORNIA",-118.243685,34.052234
1802437,1691738,CERTIFIED,GLOBAL TECHNICAL SOFTWARE SERVICES INC,Computer Systems Analysts,SYSTEMS ANALYST,Y,65416.0,2014.0,"AKRON, OHIO",-81.519005,41.081445
1802438,2758684,CERTIFIED,BRIGHAM YOUNG UNIVERSITY,Chemists,POST DOCTORAL RESEARCH ASSISTANT IN CHEMISTRY,Y,35298.0,2011.0,"PROVO, UTAH",-111.658534,40.233844
1802439,646277,CERTIFIED,HEADSTRONG SERVICES LLC,SALES ENGINEERS,BUSINESS DEVELOPMENT MANAGER,Y,86986.0,2016.0,"NEW YORK, NEW YORK",-74.005941,40.712784
1802441,46809,DENIED,ROBERTSON IMMIGRATION LAW FIRM,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,MARKETING SPECIALIST,N,37752.0,2016.0,"RALEIGH, NORTH CAROLINA",-78.638179,35.779590
1802442,230022,CERTIFIED,"3I INFOTECH, INC.",COMPUTER PROGRAMMERS,PROGRAMMER ANALYST,N,51730.0,2016.0,"EDISON, NEW JERSEY",-74.412095,40.518715
1802443,2639925,CERTIFIED,"INTERNATIONAL TECHNOLOGIES PRO, LLC","Software Developers, Applications",QA SPECIALIST,Y,70491.0,2012.0,"WASHINGTON, DISTRICT OF COLUMBIA",-77.036871,38.907192
1802444,2282725,CERTIFIED,CAPGEMINI FINANCIAL SERVICES USA INC,Computer and Information Systems Managers,MANAGER,Y,91270.0,2012.0,"CHARLOTTE, NORTH CAROLINA",-80.843127,35.227087
1802445,27793,CERTIFIED,"ROD CAPITAL MANAGEMENT, LLC",MANAGEMENT ANALYSTS,OPERATIONS ANALYST,N,56035.0,2016.0,"VENICE, CALIFORNIA",-118.469483,33.985047
1802447,512940,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,COMPUTER SYSTEMS ENGINEERS,COMPUTER SYSTEMS ENGINEER,N,63856.0,2016.0,"ST. PAUL, MINNESOTA",-93.089958,44.953703
1802448,229309,CERTIFIED,"DVR SOFTEK, INC",COMPUTER PROGRAMMERS,PROGRAMMER ANALYST,Y,73632.0,2016.0,"OWINGS MILLS, MARYLAND",-76.780253,39.419550
1802449,1570345,CERTIFIED,UST GLOBAL INC,Commercial and Industrial Designers,ENGINEERING LEAD-MECHANICAL,Y,51542.0,2014.0,"SOUTHFIELD, MICHIGAN",-83.221873,42.473369
1802450,1113570,CERTIFIED,"LANCESOFT, INC.",MANAGEMENT ANALYSTS,BUSINESS SYSTEM ANALYST,Y,42661.0,2015.0,"CHARLOTTE, NORTH CAROLINA",-80.843127,35.227087
1802451,826576,CERTIFIED,"VARENHORST ARCHITECTS, PC",ARCHITECTURAL AND CIVIL DRAFTERS,ARCHITECTURAL DRAFTER,Y,33051.0,2015.0,"PHILADELPHIA, PENNSYLVANIA",-75.165222,39.952584
1802452,1012621,CERTIFIED,DELOITTE TAX LLP,ACCOUNTANTS AND AUDITORS,TAX SENIOR,Y,74110.0,2015.0,"NEW YORK, NEW YORK",-74.005941,40.712784
1802453,2642182,CERTIFIED,"UNIVERSITY OF CALIFORNIA, SAN DIEGO","Engineering Teachers, Postsecondary",ASSISTANT PROFESSOR,Y,67530.0,2012.0,"LA JOLLA, CALIFORNIA",-117.271272,32.832811
1802455,2643074,CERTIFIED,UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER AT S...,"Medical Scientists, Except Epidemiologists",POSTDOCTORAL RESEARCH FELLOW,Y,34382.0,2012.0,"SAN ANTONIO, TEXAS",-98.493628,29.424122
1802456,1189924,CERTIFIED,SYNTEL INC,COMPUTER SYSTEMS ANALYSTS,PROGRAMMER ANALYST,Y,58677.0,2015.0,"SCOTTSDALE, ARIZONA",-111.926052,33.494170
1802457,420734,CERTIFIED,REED ELSEVIER INC. (LEXISNEXIS DIVISION),"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",SOFTWARE ENGINEER III,Y,88005.0,2016.0,"RALEIGH, NORTH CAROLINA",-78.638179,35.779590

In [6]:
count_nan = len(train) - train.count()

In [8]:
train[train.JOB_TITLE.str.contains('TECHNICAL CONSULTANT',case=False)==True]

,Unnamed: 0,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
44,1333364,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,TECHNICAL CONSULTANT,Y,70762.0,2014.0,"HARLEYSVILLE, PENNSYLVANIA",-75.387121,40.279548
718,2819186,CERTIFIED,MOURI TECH LLC,Computer Programmers,SAP TECHNICAL CONSULTANT,Y,52395.0,2011.0,"DALLAS, TEXAS",-96.796988,32.776664
1084,380266,CERTIFIED,"RESOURCE LOGISTICS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",SAP SOLUTION MANAGER TECHNICAL CONSULTANT,Y,117458.0,2016.0,"ISSAQUAH, WASHINGTON",-122.032619,47.530101
1372,106511,CERTIFIED,"POWERTEAM, LLC",COMPUTER SYSTEMS ANALYSTS,CRM TECHNICAL CONSULTANT,N,56514.0,2016.0,"CHICAGO, ILLINOIS",-87.629798,41.878114
1468,348363,CERTIFIED,"TESSITURA NETWORK, LLC","SOFTWARE DEVELOPERS, APPLICATIONS",TECHNICAL CONSULTANT - NORTH AMERICA,Y,94869.0,2016.0,"SAN ANTONIO, TEXAS",-98.493628,29.424122
1507,1328606,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,Computer Systems Analysts,SR. TECHNICAL CONSULTANT,Y,76502.0,2014.0,"HOUSTON, TEXAS",-95.369803,29.760427
1737,834357,CERTIFIED,"HIGHPOINT SOLUTIONS, LLC","SOFTWARE DEVELOPERS, APPLICATIONS",SENIOR TECHNICAL CONSULTANT,Y,97406.0,2015.0,"EAST NORRITON, PENNSYLVANIA",-75.336569,40.151774
2033,2205621,CERTIFIED,MOURI TECH LLC,Computer Programmers,SAP TECHNICAL CONSULTANT,Y,56597.0,2013.0,"WOODCLIFF LAKE, NEW JERSEY",-74.066530,41.023430
3172,2693447,CERTIFIED,MOURI TECH. LLC,Computer Programmers,SAP TECHNICAL CONSULTANT,Y,52395.0,2011.0,"DALLAS, TEXAS",-96.796988,32.776664
3221,2833769,CERTIFIED,"PERFICIENT, INC.",Computer Programmers,LEAD TECHNICAL CONSULTANT,Y,70907.0,2011.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208
3301,1329347,CERTIFIED,"RITE PROS, INC.","Software Developers, Applications",TECHNICAL CONSULTANT,Y,61173.0,2014.0,"PORTLAND, MAINE",-70.255326,43.661471
3561,2465689,CERTIFIED,"MICROEXCEL, INC.",Computer Systems Analysts,SAP TECHNICAL CONSULTANT,Y,51813.0,2012.0,"HOLLAND, MICHIGAN",-86.108930,42.787523
4241,240596,CERTIFIED,"GV INVESTMENT & MANAGEMENT SERVICES, INC.",COMPUTER PROGRAMMERS,TECHNICAL CONSULTANT,Y,73424.0,2016.0,"MILPITAS, CALIFORNIA",-121.899574,37.432334
4605,1495771,CERTIFIED,DIONA TECHNOLOGIES (US) INC,"Software Developers, Systems Software",SR./PRINCIPAL TECHNICAL CONSULTANTS,Y,81806.0,2014.0,"JEFFERSON CITY, MISSOURI",-92.173516,38.576702
5000,420137,CERTIFIED,LITMUS7 SYSTEMS CONSULTING INC.,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",SENIOR TECHNICAL CONSULTANT- DEVOPS,Y,102357.0,2016.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
5643,713285,CERTIFIED,"GSPANN TECHNOLOGIES, INC.","COMPUTER SYSTEMS ANALYSTS, NON R&D",TECHNICAL CONSULTANT,Y,63357.0,2015.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
5646,322902,CERTIFIED,ACCENTURE LLP,"SOFTWARE DEVELOPERS, APPLICATIONS",TECHNICAL CONSULTANT,N,68931.0,2016.0,"CHICAGO, ILLINOIS",-87.629798,41.878114
5963,717228,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,COMPUTER SYSTEMS ENGINEERS/ARCHITECTS,SENIOR TECHNICAL CONSULTANT,Y,64314.0,2015.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
6297,2072785,CERTIFIED,"PERFICIENT, INC.","Software Developers, Applications",SENIOR TECHNICAL CONSULTANT,Y,75462.0,2013.0,"ST. LOUIS, MISSOURI",-90.199404,38.627003
7052,2360950,CERTIFIED,LARSEN &TOUBRO INFOTECH LIMITED,Computer Programmers,TECHNICAL CONSULTANT,Y,52478.0,2012.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
8035,1606204,CERTIFIED,OLR AMERICA INC.,"Software Developers, Applications",SENIOR TECHNICAL CONSULTANT,Y,106205.0,2014.0,"MINNEAPOLIS, MINNESOTA",-93.265011,44.977753
8066,262107,CERTIFIED,IBM INDIA PRIVATE LIMITED,COMPUTER PROGRAMMERS,SAP TECHNICAL CONSULTANT,N,61610.0,2016.0,"FREEPORT, MAINE",-70.103120,43.857006
8241,511343,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,SOFTWARE QUALITY ASSURANCE ENGINEERS AND TESTERS,SENIOR TECHNICAL CONSULTANT,Y,89086.0,2016.0,"HUNT VALLEY, MARYLAND",-76.658507,39.490001
8785,312774,CERTIFIED,"TECH MAHINDRA (AMERICAS),INC.","SOFTWARE DEVELOPERS, APPLICATIONS",TECHNICAL CONSULTANT,Y,75338.0,2016.0,"ATLANTA, GEORGIA",-84.387982,33.748995
9216,1731852,CERTIFIED,"PERFICIENT, INC.","Software Developers, Applications",LEAD TECHNICAL CONSULTANT,Y,88941.0,2014.0,"ATLANTA, GEORGIA",-84.387982,33.748995
10930,129336,CERTIFIED,APTTUS CORPORATION,COMPUTER SYSTEMS ANALYSTS,"ASSOCIATE, TECHNICAL CONSULTANT",Y,74922.0,2016.0,"SAN MATEO, CALIFORNIA",-122.325525,37.562992
11150,108360,CERTIFIED,"GSPANN TECHNOLOGIES, INC.",COMPUTER SYSTEMS ANALYSTS,SENIOR TECHNICAL CONSULTANT,Y,108493.0,2016.0,"MILPITAS, CALIFORNIA",-121.899574,37.432334
11172,2319747,CERTIFIED,"BROADRIDGE FINANCIAL SOLUTIONS, INC.",Computer Systems Analysts,TECHNICAL CONSULTANT,Y,89398.0,2012.0,"HINGHAM, MASSACHUSETTS",-70.889759,42.241817
11451,862152,CERTIFIED,LITMUS7 SYSTEMS CONSULTING INC.,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",SENIOR TECHNICAL CONSULTANT,Y,100006.0,2015.0,"SAN BRUNO, CALIFORNIA",-122.411083,37.630490
11473,1737960,CERTIFIED,CLOUD SHERPAS LLC,Computer Systems Analysts,SENIOR TECHNICAL CONSULTANT,Y,91499.0,2014.0,"ATLANTA, GEORGIA",-84.387982,33.748995
...,...,...,...,...,...,...,...,...,...,...,...
1791488,1670098,CERTIFIED,SYSTIME COMPUTER CORPORATION,"Software Developers, Applications",TECHNICAL CONSULTANT,Y,66976.0,2014.0,"TONAWANDA, NEW YORK",-78.880315,43.020335
1792715,1947123,CERTIFIED,"MICROEXCEL, INC",Computer Programmers,SAP TECHNICAL CONSULTANT,Y,45635.0,2013.0,"DEERFIELD, ILLINOIS",-87.844512,42.171136
1792799,905111,CERTIFIED,"ERP ANALYSTS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",PEOPLESOFT TECHNICAL CONSULTANT,Y,62421.0,2015.0,"DUBLIN, OHIO",-83.114077,40.099229
1793568,1376245,CERTIFIED,MOURI TECH LLC,Computer Programmers,SAP TECHNICAL CONSULTANT,Y,80787.0,2014.0,"HERNDON, VIRGINIA",-77.386098,38.969555
1793627,776575,CERTIFIED,IGATE TECHNOLOGIES INC.,COMPUTER SYSTEMS ANALYSTS,TECHNICAL CONSULTANT,Y,46904.0,2015.0,"ATLANTA, GEORGIA",-84.387982,33.748995
1793768,366517,CERTIFIED,ANIMATO TECHNOLOGIES CORPORATION,"SOFTWARE DEVELOPERS, APPLICATIONS",TECHNICAL CONSULTANT,Y,98883.0,2016.0,"DALLAS, TEXAS",-96.796988,32.776664
1794582,153056,CERTIFIED,"GSPANN TECHNOLOGIES, INC.",COMPUTER SYSTEMS ANALYSTS,TECHNICAL CONSULTANT,Y,74922.0,2016.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
1794655,143633,CERTIFIED,"GSPANN TECHNOLOGIES, INC.",COMPUTER SYSTEMS ANALYSTS,SR. TECHNICAL CONSULTANT,Y,127837.0,2016.0,"MILPITAS, CALIFORNIA",-121.899574,37.432334
1794888,1012175,CERTIFIED,"EWORKPLACE SOLUTIONS, INC.","SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",TECHNICAL CONSULTANT,Y,70096.0,2015.0,"LAGUNA HILLS, CALIFORNIA",-117.696282,33.590277
1794955,853801,CERTIFIED,IBM INDIA PRIVATE LIMITED,COMPUTER PROGRAMMERS,ORACLE-JDE TECHNICAL CONSULTANT,Y,64147.0,2015.0,"SAINT LOUIS, MONTANA",NaN,NaN
1795494,1206067,CERTIFIED,COLLABERA INC.,COMPUTER SYSTEMS ANALYSTS,SAP TECHNICAL CONSULTANT,Y,53913.6,2015.0,"WORTHINGTON, OHIO",-83.017962,40.093119
1795608,1425860,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,"Software Developers, Applications",SENIOR TECHNICAL CONSULTANT,Y,72987.0,2014.0,"NEW YORK, NEW YORK",-74.005941,40.712784
1796313,513381,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,BUSINESS INTELLIGENCE ANALYSTS,SENIOR TECHNICAL CONSULTANT,Y,75733.0,2016.0,"WARREN, NEW JERSEY",-74.500480,40.634249
1796612,2605911,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,"Business Operations Specialists, All Other*",ASSOCIATE TECHNICAL CONSULTANT,Y,35194.0,2012.0,"MIAMI, FLORIDA",-80.191790,25.761680
1796959,1942965,CERTIFIED,"PERITUS, INC.",Computer Systems Analysts,SAP TECHNICAL CONSULTANT,Y,72405.0,2013.0,"PORTLAND, OREGON",-122.676482,45.523062
1798028,871584,CERTIFIED,LITMUS7 SYSTEMS CONSULTING INC.,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",SENIOR TECHNICAL CONSULTANT,Y,100006.0,2015.0,"SAN BRUNO, CALIFORNIA",-122.411083,37.630490
1798466,310693,CERTIFIED,"TECH MAHINDRA (AMERICAS),INC.","SOFTWARE DEVELOPERS, APPLICATIONS",TECHNICAL CONSULTANT,N,69950.0,2016.0,"SCHENECTADY, NEW YORK",-73.939569,42.814243
1798815,1756108,CERTIFIED,IBM INDIA PRIVATE LIMITED,Computer Programmers,BPCS TECHNICAL CONSULTANT,Y,68016.0,2014.0,"ROCK HILL, SOUTH CAROLINA",-81.025078,34.924867
1798846,928540,CERTIFIED,"PERFICIENT, INC.",COMPUTER PROGRAMMERS,ASSOCIATE TECHNICAL CONSULTANT,Y,50315.0,2015.0,"ST. LOUIS, MISSOURI",-90.199404,38.627003
1799848,1900074,CERTIFIED,AXWAY INC.,Computer Programmers,TECHNICAL CONSULTANT,Y,50336.0,2013.0,"DALLAS, TEXAS",-96.796988,32.776664
1799945,1558864,CERTIFIED,BOKANYI CONSULTING INC.,"Software Developers, Applications",SR. SAP TECHNICAL CONSULTANT,Y,112133.0,2014.0,"HOUSTON, TEXAS",-95.369803,29.760427
1800003,1544456,CERTIFIED,"SAP AMERICA, INC.",Computer Systems Analysts,TECHNICAL CONSULTANT III,Y,80912.0,2014.0,"GREENSBORO, NORTH CAROLINA",-79.791975,36.072635
1800665,2632625,CERTIFIED,"PERFICIENT, INC.",Computer Programmers,LEAD TECHNICAL CONSULTANT,Y,62254.0,2012.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
1800930,1639087,CERTIFIED,"VEDASOFT, INC.",Computer Systems Analysts,SAP INTEGRATION TECHNICAL CONSULTANT,Y,84323.0,2014.0,"DALLAS, TEXAS",-96.796988,32.776664
1801023,344648,CERTIFIED,"TECH MAHINDRA (AMERICAS),INC.","SOFTWARE DEVELOPERS, APPLICATIONS",TECHNICAL CONSULTANT,Y,78978.0,2016.0,"OVERLAND PARK, KANSAS",-94.670792,38.982228
1801226,1472591,CERTIFIED,"GLOBAL TECH & RESOURCES, INC.","Software Developers, Applications",TECHNICAL CONSULTANT,Y,62712.0,2014.0,"ROLLING MEADOWS, ILLINOIS",-88.013127,42.084194
1801568,2977647,DENIED,TALEND INC.,Sales Engineers,TECHNICAL CONSULTANT,Y,80496.0,2011.0,"MEMPHIS, TENNESSEE",-90.048980,35.149534
1802081,107002,CERTIFIED,LARSEN AND TOUBRO INFOTECH LIMITED,COMPUTER SYSTEMS ANALYSTS,TECHNICAL CONSULTANT,Y,70762.0,2016.0,"EDISON, NEW JERSEY",-74.412095,40.518715
1802170,1182018,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,COMPUTER SYSTEMS ANALYSTS,SENIOR TECHNICAL CONSULTANT,Y,86070.0,2015.0,"EDISON, NEW JERSEY",-74.412095,40.518715
1802385,1082876,CERTIFIED,"UMT CONSULTING GROUP, LLC","SOFTWARE DEVELOPERS, APPLICATIONS",TECHNICAL CONSULTANT,Y,73445.0,2015.0,"NEW YORK, NEW YORK",-74.005941,40.712784

In [9]:
train_soc_na=train[train.SOC_NAME.isna()]

In [10]:
train_soc_na

,Unnamed: 0,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
44,1333364,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,TECHNICAL CONSULTANT,Y,70762.0,2014.0,"HARLEYSVILLE, PENNSYLVANIA",-75.387121,40.279548
57,2902632,CERTIFIED,WIPRO LIMITED,NaN,DATABASE ADMINISTRATOR,Y,59654.0,2011.0,"IRVING, TEXAS",-96.948894,32.814018
80,1778133,DENIED,EMILY BOLL,NaN,FITNESS TRAINER,N,37440.0,2014.0,"HONOLULU, HAWAII",-157.858333,21.306944
137,2553233,CERTIFIED,BROADCOM CORPORATION,NaN,"ENGINEER, PRINCIPAL - SOFTWARE DEVELOPMENT",Y,142875.0,2012.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
426,2338705,CERTIFIED,"COMPUTERIZED ASSESSMENTS AND LEARNING, LLC",NaN,SENIOR JAVA WEB DEVELOPER/ PROGRAMMER,Y,50939.2,2012.0,"LAWRENCE, KANSAS",-95.235250,38.971669
447,2852120,CERTIFIED,WIPRO LIMITED,NaN,BUSINESS SYSTEM ANALYST,Y,72613.0,2011.0,"DUBLIN, OHIO",-83.114077,40.099229
1164,1687223,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,COMPUTER SYSTEMS ENGINEER,Y,45552.0,2014.0,"WARREN, NEW JERSEY",-74.500480,40.634249
1260,1426083,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,IT PROJECT MANAGER,Y,71053.0,2014.0,"FARMINGTON, CONNECTICUT",-72.795027,41.736030
1294,2877209,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,COMPUTER PROGRAMMER ANALYST,Y,75379.0,2011.0,"NEW BRUNSWICK, NEW JERSEY",-74.451819,40.486216
1535,1787362,CERTIFIED,UNIVERSITY OF MICHIGAN,NaN,FINANCIAL SPECIALIST ASSOCIATE,Y,28434.0,2013.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
1630,2935657,CERTIFIED,APPLE INC.,NaN,SW DEVELOP ENG 3,Y,99653.0,2011.0,"CUPERTINO, CALIFORNIA",-122.032182,37.322998
1730,1774015,CERTIFIED,LARSEN & TOUBRO TECHNOLOGY SERVICES LTD,NaN,DOCUMENT MANAGEMENT SYSTEM ENGINEER,Y,43618.0,2014.0,"HOUSTON, TEXAS",-95.369803,29.760427
1835,1842463,CERTIFIED,IBM CORPORATION,NaN,MANAGEMENT CONSULTANT,Y,100984.0,2013.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
1902,2176141,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,PROJECT MANAGER,Y,71053.0,2013.0,"HARTFORD, CONNECTICUT",-72.685093,41.763711
2019,2753769,CERTIFIED,WIPRO LIMITED,NaN,BUSINESS SYSTEM ANALYST LEVEL - 3,Y,92830.0,2011.0,"ALVISO, CALIFORNIA",-121.976138,37.426167
2206,2777342,CERTIFIED,IBM INDIA PVT. LTD.,NaN,SENIOR CONSULTANT,Y,62795.0,2011.0,"SAN RAMON, CALIFORNIA",-121.978015,37.779927
2223,2885468,CERTIFIED,TISHA ENTERPRISE INC.,NaN,COMPUTER PROGRAMMER ANALYST,Y,58323.0,2011.0,"TOPEKA, KANSAS",-95.689019,39.055823
2658,2726186,CERTIFIED,"DUNNHUMBY USA, LLC",NaN,"SENIOR ASSOCIATE, ANALYST",Y,48776.0,2011.0,"CINCINNATI, OHIO",-84.512020,39.103118
2694,2620027,CERTIFIED,JPMORGAN CHASE & CO,NaN,VICE PRESIDENT - INVESTMENT BANK TECHNOLOGY,Y,108867.0,2012.0,"HOUSTON, TEXAS",-95.369803,29.760427
2804,1948716,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,IT PROJECT MANAGER,Y,50419.0,2013.0,"DENVER, COLORADO",-104.990251,39.739236
2902,1307813,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,SOFTWARE ENGINEER AND TESTER,Y,65624.0,2014.0,"ALLENTOWN, PENNSYLVANIA",-75.490183,40.608430
2972,1897497,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,BUSINESS SYSTEMS ANALYST,Y,45094.0,2013.0,"EDISON, NEW JERSEY",-74.412095,40.518715
3076,1826636,CERTIFIED,IBM CORPORATION,NaN,STAFF SOFTWARE ENGINEER,Y,87006.0,2013.0,"HERNDON, VIRGINIA",-77.386098,38.969555
3087,2943067,CERTIFIED,MK INFOTECH LLC,NaN,SOFTWARE QUALITY ASSURANCE ANALYST,Y,73154.0,2011.0,"BERWYN, PENNSYLVANIA",-75.439593,40.045824
3104,2693772,CERTIFIED,WIPRO LIMITED,NaN,PROGRAMMER ANALYST,Y,76939.0,2011.0,"BEVERLY, MASSACHUSETTS",-70.880049,42.558428
3272,2811353,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,COMPUTER PROGRAMMER,Y,54163.0,2011.0,"WARREN, NEW JERSEY",-74.500480,40.634249
3369,1518864,CERTIFIED,THE OHIO NATIONAL LIFE INSURANCE COMPANY,NaN,VARIABLE ANNUITY HEDGING - QUANTITATIVE ANALYST,Y,75566.0,2014.0,"CINCINNATI, OHIO",-84.512020,39.103118
3430,2333572,CERTIFIED,SPEECH SOFT SOLUTIONS FORMERLY SPEECH-SOFT LLC,NaN,IVR SPEECH APPLICATION ANALYST,Y,69930.0,2012.0,"PLANO, TEXAS",-96.698886,33.019843
3570,2838241,CERTIFIED,TRINUS CORPORATION,NaN,SOFTWARE ENGINEER,Y,95597.0,2011.0,"SAN DIEGO, CALIFORNIA",-117.161084,32.715738
3768,1999238,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,COMPUTER SYSTEMS ENGINEER,Y,50419.0,2013.0,"DENVER, COLORADO",-104.990251,39.739236
...,...,...,...,...,...,...,...,...,...,...,...
1794342,2904339,CERTIFIED,WIPRO LIMITED,NaN,SYSTEM ADMINISTRATOR,Y,63419.0,2011.0,"IRVING, TEXAS",-96.948894,32.814018
1794870,2694224,CERTIFIED,IBM INDIA PRIVATE LIMITED,NaN,COMPUTER PROGRAMMER,Y,78083.0,2011.0,"NOVATO, CALIFORNIA",-122.569703,38.107420
1795416,2391285,CERTIFIED,THE SHERWIN-WILLIAMS COMPANY,NaN,SENIOR ORACLE SUPPLY CHAIN ANALYST,Y,83533.0,2012.0,"CLEVELAND, OHIO",-81.694361,41.499320
1795870,1491936,CERTIFIED,UNIVERSITY OF MICHIGAN,NaN,POSTDOCTORAL RESEARCH FELLOW,Y,27622.0,2014.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
1795921,2383326,CERTIFIED,"BROCADE COMMUNICATIONS SYSTEMS, INC.",NaN,SOFTWARE ENGINEER,Y,84115.0,2012.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208
1795981,1597701,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,COMPUTER SYSTEMS ENGINEER,Y,63274.0,2014.0,"WARREN, NEW JERSEY",-74.500480,40.634249
1796145,2876061,CERTIFIED,"ALPHA TECHNOLOGIES, INC.",NaN,COMPUTER PROGRAMMER ANALYST,Y,56576.0,2011.0,"GLEN BURNIE, MARYLAND",-76.624689,39.162608
1796696,2993734,CERTIFIED,"PROFICIENT BUSINESS SYSTEMS, INC.",NaN,DEVELOPER,Y,51376.0,2011.0,"LEXINGTON, KENTUCKY",-84.503716,38.040584
1796976,2790676,CERTIFIED,TECHNICAL STRATEGIES INC.,NaN,SOFTWARE ENGINEER,Y,60029.0,2011.0,"ROCHESTER, NEW YORK",-77.610922,43.161030
1797726,1955617,CERTIFIED,MOORE NURSES LLC,NaN,PEDIATRIC INTENSIVE CARE CLINICAL NURSE SPECIA...,Y,77334.0,2013.0,"OAKLAND, CALIFORNIA",-122.271114,37.804364
1798239,1658970,CERTIFIED,RS SOFTWARE (INDIA) LTD.,NaN,SENIOR SOFTWARE ENGINEER,Y,58822.0,2014.0,"FOSTER CITY, CALIFORNIA",-122.271079,37.558547
1798402,2169932,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,PROJECT MANAGER,Y,62566.0,2013.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
1798445,2833134,CERTIFIED,WIPRO LIMITED,NaN,PROGRAMMER ANALYST,Y,58490.0,2011.0,"HOUSTON, TEXAS",-95.369803,29.760427
1798605,1541450,CERTIFIED,"BUCCANEER COMPUTER SYSTEMS & SERVICE, INC.",NaN,SENIOR SCIENTIST,Y,76960.0,2014.0,"WEST DES MOINES, IOWA",-93.711332,41.577211
1798855,2907744,CERTIFIED,IBM INDIA PVT. LTD.,NaN,APPLICATION DEVELOPER,Y,58406.0,2011.0,"ALBANY, NEW YORK",-73.756232,42.652579
1798897,1801967,CERTIFIED,"TELLABS NORTH AMERICA, INC.",NaN,STAFF ENGINEER,Y,128294.0,2013.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
1799003,2875840,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,COMPUTER SOFTWARE ENGINEER,Y,55370.0,2011.0,"SANTA ANA, CALIFORNIA",-117.867834,33.745573
1799209,1737842,CERTIFIED,LARSEN & TOUBRO INFOTECH LIMITED,NaN,COMPUTER SYSTEMS ENGINEER,Y,42536.0,2014.0,"SANTA ANA, CALIFORNIA",-117.867834,33.745573
1799327,2776549,CERTIFIED,IBM INDIA PVT. LTD.,NaN,SENIOR SOFTWARE ENGINEER,Y,63586.0,2011.0,"WESTMONT, ILLINOIS",-87.975617,41.795864
1799952,2715795,CERTIFIED,WIPRO LIMITED,NaN,PROGRAMMER ANALYST,Y,63024.0,2011.0,"ATLANTA, GEORGIA",-84.387982,33.748995
1800097,2719099,CERTIFIED,"INFINITE SOLUTIONS, INC.",NaN,SOFTWARE ENGINEER,Y,61443.0,2011.0,"SACRAMENTO, CALIFORNIA",-121.494400,38.581572
1800367,2122408,CERTIFIED,LARSEN & TOUBRO LIMITED,NaN,COMPUTER SYSTEMS ENGINEER,Y,41766.0,2013.0,"BURR RIDGE, ILLINOIS",-87.918392,41.748920
1800487,1609686,DENIED,HAITIAN AMERICAN CULTURAL AND SOCIAL ORGANIZATION,NaN,COMMUNITY HEALTH WORKERS - 21-1094.00,Y,31200.0,2014.0,"SPRING VALLEY, NEW YORK",-74.043752,41.113151
1800670,1481862,CERTIFIED,LARSEN & TOUBRO LIMITED,NaN,COMPUTER SYSTEMS ENGINEER,Y,50086.0,2014.0,"HESSTON, KANSAS",-97.431427,38.138344
1800866,2966136,CERTIFIED,"DADA ENTERTAINMENT, INC.",NaN,COMPUTER ANALYST/PROGRAMMER,Y,52478.0,2011.0,"NEW YORK, NEW YORK",-74.005941,40.712784
1801042,2557879,CERTIFIED,POPULUS GROUP,NaN,SOFTWARE APPLICATION ENGINEER,Y,69888.0,2012.0,"COLUMBUS, OHIO",-82.998794,39.961176
1801671,2849587,CERTIFIED,"AVIVA INVESTORS NORTH AMERICA, INC.",NaN,APPLICATIONS DEVELOPER,Y,56742.0,2011.0,"DES MOINES, IOWA",-93.609106,41.600545
1802138,1843216,CERTIFIED,"IMBUESYS, INC.",NaN,QUALITY ASSURANCE ANALYST,Y,47216.0,2013.0,"NAPERVILLE, ILLINOIS",-88.153535,41.750839
1802280,1338407,CERTIFIED,"DUNNHUMBY USA, LLC",NaN,SOFTWARE ENGINEER,Y,71864.0,2014.0,"BOSTON, MASSACHUSETTS",-71.058880,42.360083
1802406,2430510,CERTIFIED,ALCATEL-LUCENT USA INC.,NaN,SOFTWARE DEVELOPER,Y,113152.0,2012.0,"MURRAY HILL, NEW JERSEY",-74.401265,40.695141

In [41]:
train_temp=train[(train['JOB_TITLE']== 'TECHNOLOGY LEAD - US') 
                 &(train['SOC_NAME']=='Computer Systems Analysts')
                 &(train['EMPLOYER_NAME']=='INFOSYS LIMITED') ]

In [42]:
train_temp

,Unnamed: 0,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
49,2628154,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,72592.0,2012.0,"HOUSTON, TEXAS",-95.369803,29.760427
168,2061362,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,68162.0,2013.0,"TAMPA, FLORIDA",-82.457178,27.950575
311,1670933,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,79269.0,2014.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208
494,1838117,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,71510.0,2013.0,"PHILADELPHIA, PENNSYLVANIA",-75.165222,39.952584
606,1317690,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,73445.0,2014.0,"NEWARK, DELAWARE",-75.749657,39.683723
886,2100168,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,63066.0,2013.0,"MOORESVILLE, NORTH CAROLINA",-80.810072,35.584860
931,1385001,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,79268.8,2014.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
1193,2058765,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,59259.0,2013.0,"NORTHBROOK, ILLINOIS",-87.828955,42.127527
1285,1834101,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,59259.0,2013.0,"HOFFMAN ESTATES, ILLINOIS",-88.122720,42.062991
1410,2125793,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,66872.0,2013.0,"ATLANTA, GEORGIA",-84.387982,33.748995
1589,1883209,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,70533.0,2013.0,"KEENE, NEW HAMPSHIRE",-72.278141,42.933692
1609,1963525,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,67038.0,2013.0,"SPRINGFIELD, MASSACHUSETTS",-72.589811,42.101483
1734,2560387,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,76939.0,2012.0,"BELLEVUE, WASHINGTON",-122.201516,47.610150
2087,2063371,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,67038.0,2013.0,"MINNEAPOLIS, MINNESOTA",-93.265011,44.977753
2191,1806394,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,71240.0,2013.0,"PLANO, TEXAS",-96.698886,33.019843
2435,1822900,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,68390.0,2013.0,"FARMINGTON HILLS, MICHIGAN",-83.367717,42.498994
2523,1804061,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,75878.0,2013.0,"NEW YORK, NEW YORK",-74.005941,40.712784
2524,1690413,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,64314.0,2014.0,"KANSAS CITY, MISSOURI",-94.578567,39.099727
2586,1929448,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,83637.0,2013.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208
2587,2161236,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,62525.0,2013.0,"HOFFMAN ESTATES, ILLINOIS",-88.122720,42.062991
2655,1763311,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,76211.0,2014.0,"NEWARK, NEW JERSEY",-74.172367,40.735657
2811,1708836,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,65083.0,2014.0,"FORT WORTH, TEXAS",-97.330766,32.755488
3335,2089632,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,61589.0,2013.0,"SALT LAKE CITY, UTAH",-111.891047,40.760779
3717,1825907,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,72675.0,2013.0,"WILMINGTON, DELAWARE",-75.539788,39.739072
3928,1381779,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,68661.0,2014.0,"SAINT LOUIS, MISSOURI",-90.199404,38.627003
4034,1814798,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,64896.0,2013.0,"SCARBOROUGH, MAINE",-70.334492,43.590197
4044,2167391,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,77334.0,2013.0,"CENTENNIAL(CO), COLORADO",NaN,NaN
4725,1413740,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,55890.0,2014.0,"SOUTH BURLINGTON, VERMONT",-73.170960,44.466994
5082,1604669,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,77626.0,2014.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
5654,1666741,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,54538.0,2014.0,"ROANOKE, VIRGINIA",-79.941427,37.270970
...,...,...,...,...,...,...,...,...,...,...,...
1796359,2227398,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,70803.0,2013.0,"CHARLOTTE, NORTH CAROLINA",-80.843127,35.227087
1796641,1942778,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,75878.0,2013.0,"NEW YORK, NEW YORK",-74.005941,40.712784
1797057,1734346,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,85322.0,2014.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
1797135,1417559,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,62525.0,2014.0,"NORTHBROOK, ILLINOIS",-87.828955,42.127527
1797184,2552214,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,65187.0,2012.0,"MIAMI, FLORIDA",-80.191790,25.761680
1797934,1928773,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,83636.8,2013.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208
1797966,1341640,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,70845.0,2014.0,"PLANO, TEXAS",-96.698886,33.019843
1797999,1907137,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,75878.0,2013.0,"NEW YORK, NEW YORK",-74.005941,40.712784
1798043,1688283,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,72779.0,2014.0,"BOSTON, MASSACHUSETTS",-71.058880,42.360083
1798151,1388746,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,74298.0,2014.0,"BEAVERTON, OREGON",-122.803710,45.487062
1798182,1756863,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,61776.0,2014.0,"ATLANTA, GEORGIA",-84.387982,33.748995
1798224,1806353,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,71240.0,2013.0,"PLANO, TEXAS",-96.698886,33.019843
1798405,1758620,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,62067.0,2014.0,"BENTONVILLE, ARKANSAS",-94.208817,36.372854
1798545,1894301,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,75878.0,2013.0,"VALHALLA, NEW YORK",-73.775133,41.074819
1798698,2565920,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,73091.0,2012.0,"MIAMISBURG, OHIO",-84.286608,39.642836
1799050,2167726,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,84469.0,2013.0,"BRADENTON, FLORIDA",-82.574819,27.498928
1799178,1843379,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,83636.8,2013.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
1799556,1925866,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,83636.8,2013.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
1799614,2571229,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,67122.0,2012.0,"PLANO, TEXAS",-96.698886,33.019843
1799991,1735579,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,67808.0,2014.0,"BOLINGBROOK, ILLINOIS",-88.068395,41.698642
1800006,1834204,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,66872.0,2013.0,"ALPHARETTA, GEORGIA",-84.294090,34.075376
1800229,1916686,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,68390.0,2013.0,"FARMINGTON HILLS, MICHIGAN",-83.367717,42.498994
1800862,2549007,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,74318.0,2012.0,"HARTFORD, CONNECTICUT",-72.685093,41.763711
1801153,1424401,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,61838.0,2014.0,"SALT LAKE CITY, UTAH",-111.891047,40.760779
1801186,1325872,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,68661.0,2014.0,"HAZELWOOD, MISSOURI",-90.370949,38.771440
1801538,1828160,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,68099.0,2013.0,"HOOVER, ALABAMA",-86.811378,33.405387
1801654,2567294,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,69472.0,2012.0,"ATLANTA, GEORGIA",-84.387982,33.748995
1801811,1837196,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,74880.0,2013.0,"LOS ANGELES, CALIFORNIA",-118.243685,34.052234
1801947,1874945,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,67496.0,2013.0,"MOORESTOWN, NEW JERSEY",-74.948886,39.968882
1802341,1852731,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,72675.0,2013.0,"WILMINGTON, DELAWARE",-75.539788,39.739072

In [26]:
train.JOB_TITLE.str.replace(' ','').str.lower()

0                                      programmeranalyst
1                                sitereliabilityengineer
2                                         projectmanager
3                                       staffprosthetist
5                              assistantprojectscientist
6                                       softwareengineer
7                                      physicaltherapist
8                                  applicationsdeveloper
9                        softwareengineer/networkanalyst
10                                    managingconsultant
11                     softwaredevelopmentengineerintest
12                                       systemsengineer
13                                  facilitiesspecialist
14                                          systemtester
15         seniormechanicalengineer-performanceimproveme
16                        vicepresident,portfoliomanager
17                                    assistantprofessor
18                               associateproductmanager
19                                     programmeranalyst
20                                     technologylead-us
21                                      softwareengineer
22                                           projectlead
24                          carrierreadinesstestengineer
25                                   onlinemarketanalyst
26                                  architeturaldesigner
27                                     exemptnon-officer
28                                    computerprogrammer
29                                       systemsengineer
30                                           hospitalist
31                                            consultant
                               ...
1802423                                        tassenior
1802424                              financialspecialist
1802425                                     sqlserverdba
1802426                                          analyst
1802427                                 softwareengineer
1802428                             softwaretestengineer
1802429                            databaseadministrator
1802430                            web/databasedeveloper
1802431                                       eslteacher
1802433                               testengineerlevel1
1802435                                     leadengineer
1802436                                programmeranalyst
1802437                                   systemsanalyst
1802438         postdoctoralresearchassistantinchemistry
1802439                       businessdevelopmentmanager
1802441                              marketingspecialist
1802442                                programmeranalyst
1802443                                     qaspecialist
1802444                                          manager
1802445                                operationsanalyst
1802447                          computersystemsengineer
1802448                                programmeranalyst
1802449                       engineeringlead-mechanical
1802450                            businesssystemanalyst
1802451                             architecturaldrafter
1802452                                        taxsenior
1802453                               assistantprofessor
1802455                       postdoctoralresearchfellow
1802456                                programmeranalyst
1802457                              softwareengineeriii
Name: JOB_TITLE, Length: 1626887, dtype: object

In [102]:
train_groupby=pd.DataFrame({'COUNT': train.groupby(['EMPLOYER_NAME','SOC_NAME','JOB_TITLE','FULL_TIME_POSITION']).size().sort_values(ascending=False)}).reset_index()

In [97]:
temp.loc[(temp['FULL_TIME_POSITION']== 'Y') 
                 &(temp['JOB_TITLE']=='TECHNOLOGY LEAD - US')
                 &(temp['EMPLOYER_NAME']=='INFOSYS LIMITED') ,'temp'] +=3

In [101]:
temp['temp']=0

In [142]:
train_groupby["FREQUENCY"]=0

In [121]:
train_groupby

,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,COUNT,FREQUENCY
0,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,8551,0
1,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY ANALYST - US,Y,8397,0
2,TATA CONSULTANCY SERVICES LIMITED,Computer Programmers,COMPUTER PROGRAMMER,Y,8041,0
3,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,TECHNOLOGY LEAD - US,Y,5211,0
4,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,TECHNOLOGY ANALYST - US,Y,4194,0
5,INFOSYS LIMITED,Computer Programmers,SYSTEMS ENGINEER - US,Y,3097,0
6,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,TECHNOLOGY ANALYST - US,N,2798,0
7,TATA CONSULTANCY SERVICES LIMITED,COMPUTER PROGRAMMERS,DEVELOPER,Y,2758,0
8,TATA CONSULTANCY SERVICES LIMITED,COMPUTER PROGRAMMERS,DEVELOPER,N,2435,0
9,WIPRO LIMITED,Computer Programmers,PROGRAMMER ANALYST,Y,2345,0
10,WIPRO LIMITED,"COMPUTER OCCUPATIONS, ALL OTHER",LEAD ENGINEER,Y,2343,0
11,GOOGLE INC.,"SOFTWARE DEVELOPERS, APPLICATIONS",SOFTWARE ENGINEER,Y,2274,0
12,INFOSYS LIMITED,Computer Systems Analysts,PROJECT MANAGER - US,Y,2254,0
13,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,TECHNOLOGY LEAD - US,Y,2141,0
14,GOOGLE INC.,"Software Developers, Applications",SOFTWARE ENGINEER,Y,2090,0
15,INFOSYS LIMITED,Computer Systems Analysts,CONSULTANT - US,Y,2076,0
16,ACCENTURE LLP,Computer Programmers,COMPUTER PROGRAMMER/CONFIGURER 2,Y,2049,0
17,MICROSOFT CORPORATION,"SOFTWARE DEVELOPERS, APPLICATIONS",SOFTWARE ENGINEER,Y,2029,0
18,INFOSYS LIMITED,COMPUTER PROGRAMMERS,SYSTEMS ENGINEER - US,Y,1793,0
19,DELOITTE CONSULTING LLP,"Software Developers, Systems Software",SENIOR CONSULTANT,Y,1778,0
20,TATA CONSULTANCY SERVICES LIMITED,WEB DEVELOPERS,DEVELOPER USER INTERFACE,N,1765,0
21,WIPRO LIMITED,"Computer Occupations, All Other",LEAD ENGINEER,Y,1737,0
22,TATA CONSULTANCY SERVICES LIMITED,Web Developers,WEB DEVELOPER,Y,1735,0
23,MICROSOFT CORPORATION,"Software Developers, Applications",SOFTWARE DEVELOPMENT ENGINEER,Y,1693,0
24,LARSEN & TOUBRO INFOTECH LIMITED,Computer Programmers,COMPUTER PROGRAMMER,Y,1650,0
25,DELOITTE CONSULTING LLP,"Software Developers, Systems Software",CONSULTANT,Y,1550,0
26,TATA CONSULTANCY SERVICES LIMITED,COMPUTER PROGRAMMERS,COMPUTER PROGRAMMER,Y,1454,0
27,INFOSYS LIMITED,"Computer Occupations, All Other",TECHNICAL TEST LEAD - US,Y,1414,0
28,TATA CONSULTANCY SERVICES LIMITED,WEB DEVELOPERS,DEVELOPER USER INTERFACE,Y,1389,0
29,MICROSOFT CORPORATION,"Software Developers, Applications",SOFTWARE DEVELOPMENT ENGINEER IN TEST,Y,1350,0
...,...,...,...,...,...,...
692372,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists",INVESTIGATOR II,Y,1,0
692373,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists",INVESTIGATOR I,Y,1,0
692374,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists",CLINICAL RESEARCH MANAGER,Y,1,0
692375,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Marketing Managers,"ASSOCIATE DIRECTOR, MARKETING - INFLUENZA",Y,1,0
692376,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists","SCIENTIFIC ASSOCIATE II, CHEMISTRY",Y,1,0
692377,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Managers, All Other",REGULATORY AFFAIRS MANAGER,Y,1,0
692378,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Managers, All Other",GLOBAL VALUE CHAIN MANAGER,Y,1,0
692379,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Management Analysts,"SIX SIGMA BLACK BELT, GLOBAL SUPPLY CHAIN",Y,1,0
692380,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Management Analysts,"MANAGER, STRATEGY REPORTING",Y,1,0
692381,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Management Analysts,"MANAGER, STRATEGIC PLANNING",Y,1,0
692382,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Management Analysts,ALLIANCE MANAGER,Y,1,0
692383,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists",RESEARCH INVESTIGATOR II,Y,1,0
692384,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists",SCIENTIST I,Y,1,0
692385,NOVASTAR LP,LOGISTICIANS,SUPPLY CHAIN MANAGER,Y,1,0
692386,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Statisticians,STATISTICAL ASSOCIATE II,Y,1,0
692387,"NOVASPECT, INC.",Electrical Engineers,CONTROL SYSTEM ENGINEER,Y,1,0
692388,"NOVASPARKS, INC.",Computer Systems Analysts,SYSTEMS ENGINEER,Y,1,0
692389,"NOVASPARKS, INC.","Computer Occupations, All Other*",SOFTWARE QUALITY ASSURANCE ENGINEER,Y,1,0
692390,"NOVASPARKS, INC.",Computer Hardware Engineers,PRINCIPAL RESEARCH ENGINEER,Y,1,0
692391,"NOVASOM, INC.",Computer Systems Analysts,BUSINESS ANALYST,Y,1,0
692392,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Statisticians,STATISTICIAN I,Y,1,0
692393,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Public Relations and Fundraising Managers,"ASSOCIATE DIRECTOR, GLOBAL PRODUCT COMMUNICATIONS",Y,1,0
692394,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists",SCIENTIST II,Y,1,0
692395,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Operations Research Analysts,BUSINESS ANALYST,Y,1,0
692396,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Network and Computer Systems Administrators,QUALITY BUSINESS ANALYST,Y,1,0
692397,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Network and Computer Systems Administrators,"BUSINESS SYSTEMS ANALYST, GLOBAL QUALITY",Y,1,0
692398,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Microbiologists,POST-DOCTORAL FELLOW,Y,1,0
692399,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",Microbiologists,DEVELOPMENT ENGINEER II,Y,1,0
692400,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.","Medical Scientists, Except Epidemiologists","SCIENTIST, PROCESS SCIENCES/PURIFICATION GROUP...",Y,1,0
692401,"""I HAVE A DREAM"" FOUNDATION",Financial Managers,DIRECTOR OF FINANCE AND ADMINISTRATION,Y,1,0

In [155]:
train_groupby.loc[(train_groupby['EMPLOYER_NAME']=='INFOSYS LIMITED'),'FREQUENCY'] +=4
train_groupby.loc[(train_groupby['JOB_TITLE']=='TECHNOLOGY LEAD'),'FREQUENCY']+=2
train_groupby.loc[(train_groupby['FULL_TIME_POSITION']=='Y'),'FREQUENCY'] +=1
a=train_groupby.sort_values(['FREQUENCY','COUNT'],ascending=[False,False]).head(1).SOC_NAME

In [154]:
train_groupby.sort_values(['FREQUENCY','COUNT'],ascending=[False,False]).head(1).SOC_NAME.values[0]

'Computer Systems Analysts'

In [156]:
train_groupby.sort_values(['FREQUENCY','COUNT'],ascending=[False,False])

,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,COUNT,FREQUENCY
13463,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD,Y,10,28
16462,INFOSYS LIMITED,Computer Programmers,TECHNOLOGY LEAD,Y,9,28
0,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,8551,20
1,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY ANALYST - US,Y,8397,20
3,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,TECHNOLOGY LEAD - US,Y,5211,20
4,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,TECHNOLOGY ANALYST - US,Y,4194,20
5,INFOSYS LIMITED,Computer Programmers,SYSTEMS ENGINEER - US,Y,3097,20
12,INFOSYS LIMITED,Computer Systems Analysts,PROJECT MANAGER - US,Y,2254,20
13,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,TECHNOLOGY LEAD - US,Y,2141,20
15,INFOSYS LIMITED,Computer Systems Analysts,CONSULTANT - US,Y,2076,20
18,INFOSYS LIMITED,COMPUTER PROGRAMMERS,SYSTEMS ENGINEER - US,Y,1793,20
27,INFOSYS LIMITED,"Computer Occupations, All Other",TECHNICAL TEST LEAD - US,Y,1414,20
31,INFOSYS LIMITED,"Computer Occupations, All Other",TEST ANALYST - US,Y,1315,20
32,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,CONSULTANT - US,Y,1298,20
35,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,PROJECT MANAGER - US,Y,1228,20
37,INFOSYS LIMITED,"Computer Occupations, All Other",TECHNOLOGY ARCHITECT - US,Y,1178,20
38,INFOSYS LIMITED,Computer Systems Analysts,ASSOCIATE CONSULTANT - US,Y,1176,20
51,INFOSYS LIMITED,"COMPUTER OCCUPATIONS, ALL OTHER",TECHNICAL TEST LEAD - US,Y,985,20
54,INFOSYS LIMITED,Computer Systems Analysts,MODULE LEAD,Y,981,20
59,INFOSYS LIMITED,"COMPUTER OCCUPATIONS, ALL OTHER",TECHNOLOGY ARCHITECT - US,Y,955,20
66,INFOSYS LIMITED,"COMPUTER OCCUPATIONS, ALL OTHER",TEST ANALYST - US,Y,842,20
68,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,LEAD CONSULTANT - US,Y,819,20
69,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,ASSOCIATE CONSULTANT - US,Y,803,20
70,INFOSYS LIMITED,Computer Systems Analysts,LEAD CONSULTANT - US,Y,801,20
71,INFOSYS LIMITED,Computer Systems Analysts,ANALYST,Y,797,20
77,INFOSYS LIMITED,"Computer Occupations, All Other",SENIOR PROJECT MANAGER - US,Y,755,20
79,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,CONSULTANT - US,Y,745,20
90,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,PROJECT MANAGER - US,Y,685,20
97,INFOSYS LIMITED,"Computer Occupations, All Other",TEST ENGINEER - US,Y,649,20
120,INFOSYS LIMITED,COMPUTER SYSTEMS ENGINEERS/ARCHITECTS,TECHNOLOGY ARCHITECT - US,Y,548,20
...,...,...,...,...,...,...
692120,"NOVEDEA SYSTEMS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",.NET DEVELOPER,N,1,0
692127,"NOVEDEA SYSTEMS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",SENIOR SOFTWARE DEVELOPER,N,1,0
692129,"NOVEDEA SYSTEMS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",SENIOR UI FRAMEWORK ENGINEER,N,1,0
692132,"NOVEL LABORATORIES, INC.",CHEMISTS,ANALYTICAL CHEMIST,N,1,0
692136,"NOVEL LABORATORIES, INC.","BUSINESS OPERATIONS SPECIALISTS, ALL OTHER",BUSINESS ANALYST,N,1,0
692141,"NOVEDEA SYSTEMS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",SYSTEMS ANALYST,N,1,0
692142,"NOVEDEA SYSTEMS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",SYSTEM ANALYST,N,1,0
692144,"NOVEDEA SYSTEMS, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",SR APPLICATIONS DEVELOPER,N,1,0
692157,"NOVATEUR TECHNOLOGIES, INC.",COMPUTER PROGRAMMERS,COMPUTER PROGRAMMER,N,1,0
692164,"NOVATION VENTURES, LLC",Financial Analysts,FINANCIAL ANALYST,N,1,0
692177,"NOVAVAX, INC.",BIOCHEMISTS AND BIOPHYSICISTS,SENIOR RESEARCH ASSOCIATE,N,1,0
692178,"NOVAVAX, INC.",BIOCHEMISTS AND BIOPHYSICISTS,SENIOR PROCESS DEVELOPMENT ASSOCIATE,N,1,0
692179,"NOVAVAX, INC.",BIOCHEMISTS AND BIOPHYSICISTS,PRODUCT SAFETY SPECIALIST,N,1,0
692180,"NOVAVAX, INC.",BIOCHEMISTS AND BIOPHYSICISTS,MANUFACTURING ASSOCIATE I,N,1,0
692181,"NOVAVAX, INC.",BIOCHEMISTS AND BIOPHYSICISTS,AUTOMATION SPECIALIST,N,1,0
692189,NOVELIS INC.,MATERIALS ENGINEERS,STAFF METALLURGY TECHNOLOGIST,N,1,0
692217,"NOVELL, INC.","COMPUTER OCCUPATIONS, ALL OTHER",TECHNICAL SUPPORT ENGINEER,N,1,0
692221,NOVELIS CORPORATION,INDUSTRIAL ENGINEERS,PROCESS ENGINEER,N,1,0
692227,"NOVEL LABORATORIES, INC.",COMPLIANCE OFFICERS,SR. REGULATORY AFFAIRS ASSOCIATE,N,1,0
692234,"NOVEL LABORATORIES, INC.",CHEMISTS,SENIOR CHEMIST,N,1,0
692243,"NOVELABORATORI, LLC",GRAPHIC DESIGNERS,USER EXPERIENCE DESIGNER,N,1,0
692245,"NOVEL LABORATORIES, INC.",TECHNICAL WRITERS,TECHNICAL WRITER,N,1,0
692269,"NOVARTIS VACCINES AND DIAGNOSTICS, INC.",BIOCHEMISTS AND BIOPHYSICISTS,SCIENTIFIC ASSOCIATE II,N,1,0
692310,NOVARTIS PHARMACEUTICALS CORPORATION,TECHNICAL WRITERS,SUBMISSION WRITER,N,1,0
692314,NOVARTIS SERVICES INC.,OPERATIONS RESEARCH ANALYSTS,LEAD BI ANALYST,N,1,0
692315,NOVARTIS SERVICES INC.,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,UNIX ENGINEER - LINUX,N,1,0
692318,NOVARTIS SERVICES INC.,COMPUTER SYSTEMS ANALYSTS,"DOMAIN LEAD, MANUFACTURING Q&AMP;M",N,1,0
692319,NOVARTIS SERVICES INC.,COMPUTER SYSTEMS ANALYSTS,COMMERCIAL IT-PROJECT MANAGER MARKET DEPLOYMEN...,N,1,0
692338,"NOVATECK FLOOR, CORP.",Financial Managers,FINANCIAL MANAGER,N,1,0
692365,NOVATECH ELECTRO-LUMINESCENT,Sales Engineers,"SALES ENGINEER, ELECTRO-LUMINESCENT PRODUCTS",N,1,0

In [139]:
bin(7)

'0b111'

In [90]:

if not temp[(temp['FULL_TIME_POSITION']== 'Y') 
                 &(temp['JOB_TITLE']=='TECHNOLOGY LEAD - US')
                 &(temp['EMPLOYER_NAME']=='INFOSYS LIMITED') ].SOC_NAME.empty :
    print (temp[(temp['FULL_TIME_POSITION']== 'Y') 
                 &(temp['JOB_TITLE']=='TECHNOLOGY LEAD - US')
                 &(temp['EMPLOYER_NAME']=='INFOSYS LIMITED') ].SOC_NAME[0])

Computer Systems Analysts

In [31]:
train.JOB_TITLE.str.replace(' ','').str.lower().value_counts()

programmeranalyst                                        136890
softwareengineer                                          63712
computerprogrammer                                        39402
systemsanalyst                                            34234
softwaredeveloper                                         23244
businessanalyst                                           21691
computersystemsanalyst                                    19339
technologylead-us                                         17299
technologyanalyst-us                                      16039
seniorsoftwareengineer                                    14546
seniorconsultant                                          14068
consultant                                                13038
assistantprofessor                                        12620
physicaltherapist                                         11051
projectmanager                                            10933
databaseadministrator                                      9157
accountant                                                 7921
developer                                                  7430
computerprogrammeranalyst                                  7304
associate                                                  6781
researchassociate                                          6541
computersystemsengineer                                    6487
analyst                                                    6236
leadengineer                                               6115
systemsengineer-us                                         5987
programmer/analyst                                         5695
businesssystemsanalyst                                     5473
seniorsoftwaredeveloper                                    5393
marketresearchanalyst                                      5048
manager                                                    4996
                                                          ...
controlsengineer-adascontrols                                 1
as/400programmer                                              1
instructor(japanese),modernlanguages&cultures                 1
seniorstaffengineer-wirelessmodem                             1
businessrolesdeveloper                                        1
requirementsmanager                                           1
hispanicliaison                                               1
lab/qualitycontrolanalyst                                     1
businessanalyst-gis                                           1
seniorstaffaccounant                                          1
globalmarketsfinancialtechnicalproductdvlpmt.cnsltnt.         1
seniorvicepresident-customerbusiness                          1
advertising&salesmanager                                      1
productmanagementanalysti                                     1
technicallead&solutionarchitect                               1
it-webdesigner/developeriii                                   1
assistantvicepresident,ficcu.s.municipals                     1
directoroffinanceandhumanresources                            1
senioriossoftwaredeveloper                                    1
sr.analysisengineer                                           1
istechnicalteamlead(systemsanalyst)                           1
generalmanager,brandmarketing                                 1
academiccounselorinthelearningdifferencesprogram              1
countryplanning&operationsdirector                            1
packagingmechanicaldevelopmentengineer                        1
researchassociatecy/chemistry&chemicalbiology                 1
managertranslationdepartment                                  1
businessprojectseniorspecialist                               1
leadsysconsultant-sysanalysis&prg(systems                     1
graduatehardwaredesignengineer                                1
Name: JOB_TITLE, Length: 191955, dtype: int64

In [29]:
df = pd.DataFrame(np.random.randint(0, 3, (10, 4)), columns=list('abcd'))
df

   a  b  c  d
0  2  2  0  0
1  0  2  2  0
2  1  2  1  2
3  2  2  1  0
4  0  2  1  1
5  1  1  1  0
6  2  2  0  0
7  0  1  1  2
8  1  1  0  2
9  2  0  0  2

In [30]:
df.apply(pd.Series.value_counts)

   a  b  c  d
0  3  1  4  5
1  3  3  5  1
2  4  6  1  4

In [ ]:
def set_soc_code():
    """
    MAKE JOB OCT CODE 팔진수 코드를 부여해 보기 쉽게 한다  
    0o0: OTHERS 
    0o400 : COMPUTER 
    0o200 : MEDICAL
    0o100 : SCIENCES
    0o040 : EDUCATION
    0o020 : MANAGE
    0o010 : BUSSINESS
    0o004 : TECHNOLOGY
    0o002 : FINANCIAL
    0o001 : LIVESTOCK
    """
    code_computer=np.array([0o400,'com','software','programmer','project',
                   'developer','database','consultant', 'manager'])
    code_medical=np.array([0o200,'medical','doctor','physic','dentist',
                          'surgeon','nurse','psych','health'])
    code_sci=np.array([0o100,'chemist','physicist','bio','scientist',
              'clinical','math','statistic','predictive','stats'])
    code_edu=np.array([0o40,'teach','linguist','professor','school','principal'])
    code_manage=np.array([0o20,'relation','manage','operation','chief','plan','executive'])
    code_bussiness=np.array([0o10,'advertis','marketing','business','research','promotion'])
    code_tech=np.array([0o4,'techno','engineer','surveyor','carto',
             'architect','drafter','information','security'])
    code_finacial=np.array([0o2,'accountant','finan'])
    code_livestock=np.array([0o1,'water','butcher'])
    code_list=[code_computer,code_medical,code_sci,code_edu,code_manage,
               code_bussiness,code_tech,code_finacial,code_livestock]
    soc_code_array= np.array(code_list)
    return soc_code_array
soc_code_array=set_soc_code()

In [ ]:
def match_soc_code(soc_name_input) :
    soc_code_num=0o0 # 나중에 반환될값
    soc_name_series=pd.Series(str(soc_name_input).split(' ')) # 글자를 띄어쓰기 별로 구분해서 Series 화 시킨다
    soc_find=lambda x: soc_name_series[soc_name_series.str.contains('|'.join(x),case=False)].size>=1 # 람다식 함수 생성  or 를 join 으로 다 붙여준후에 contains 해주고 그게 크기를 구하는 함수
    soc_result=np.array(list(filter(soc_find,soc_code_array)))#필터를 통해 아까 람다식이 참인 것들만 반환해 준다
    soc_code_list=[int(i[0])  for i in soc_result  ]#팔진수를 인티저 형으로 받아서 더해준다
    soc_code_num=sum(soc_code_list)
    if (soc_code_num>=1) : # 카테고리화 되지 못한 항목은 0으로 유지 선택된 것은 맨앞에 1을 붙여주어 구별하기 편하게 한다.
        soc_code_num+=0o1000 
    return oct(soc_code_num) # 카테고리화 된 번호 반환

In [ ]:
train["SOC_NAME"].head(1000).map(lambda x : match_soc_code(x))

In [ ]:
train["SOC_NAME"].head(10).map(lambda x : match_soc_code(x))

In [ ]:
train["SOC_NAME"].head(100)

In [ ]:
temp=[['ddd', 'aikkt'],['og','adt'],['et','f']]
searchfor =  np.array(temp)
s = pd.Series(['cat','hat','dog','fog','pet'])
#s[s.str.contains('|'.join(searchfor),case=False)]

In [ ]:
do=lambda x: s[s.str.contains('|'.join(x),case=False)].size>=1

a=list(map(do,searchfor))
b=list(filter(do,searchfor))
c= [i[0] for i in b ]
c

In [ ]:
str="COMPUTER"
l = ['COMPUTER','SOFEWARE','PROGRAMMER',
            'PROJECT','DEVELOPER','DATA','CONSULTANT',
            'MANAGER']
def find_char(str1,list_):
    x=[i  for i in list_ if i in str1]
    return x
find_char(str,l)

In [ ]:
print ( bin (10))

In [ ]:
oct(0o10+0o20)

In [ ]:
a=0o400
a

In [ ]:
bin(a)

In [ ]:
oct(a)

In [124]:
df1 = pd.DataFrame(np.random.randint(1, 5, (10,2)), columns=['a','b'])
df1

   a  b
0  4  1
1  3  3
2  1  4
3  4  1
4  2  2
5  2  1
6  2  3
7  2  3
8  3  3
9  4  3

In [127]:
df1.sort_values(['a', 'b'], ascending=[False, False])

   a  b
9  4  3
0  4  1
3  4  1
1  3  3
8  3  3
6  2  3
7  2  3
4  2  2
5  2  1
2  1  4

In [1]:
train

NameError: name 'train' is not defined

In [6]:
df_split=np.array_split(train,4)

In [8]:
df_split[0]

,Unnamed: 0,CASE_STATUS,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
0,1349742,CERTIFIED,"INTERNATIONAL SYSTEMS TECHNOLOGIES, INC.",Computer Programmers,PROGRAMMER ANALYST,Y,61589.0,2014.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
1,789205,CERTIFIED,GOOGLE INC.,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,SITE RELIABILITY ENGINEER,Y,79144.0,2015.0,"SAN FRANCISCO, CALIFORNIA",-122.419415,37.774929
2,1617140,CERTIFIED,WIPRO LIMITED,"Computer Occupations, All Other",PROJECT MANAGER,Y,73882.0,2014.0,"EL SEGUNDO, CALIFORNIA",-118.416465,33.919180
3,2757905,CERTIFIED,"CPO SERVICES, INC.",Orthotists and Prosthetists,STAFF PROSTHETIST,Y,61589.0,2011.0,"PEORIA, ILLINOIS",-89.588986,40.693649
5,693102,DENIED,"UNIVERSITY OF CALIFORNIA, SAN DIEGO","MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",ASSISTANT PROJECT SCIENTIST,Y,42120.0,2015.0,"LA JOLLA, CALIFORNIA",-117.271272,32.832811
6,2662510,CERTIFIED,GOOGLE INC.,"Computer Software Engineers, Applications",SOFTWARE ENGINEER,Y,82035.0,2011.0,"MOUNTAIN VIEW, CALIFORNIA",-122.083851,37.386052
7,636434,CERTIFIED,"COMPREHAB, INC.",PHYSICAL THERAPISTS,PHYSICAL THERAPIST,N,64168.0,2016.0,"GASTONIA, NORTH CAROLINA",-81.187301,35.262082
8,2265757,CERTIFIED,JPMORGAN CHASE AND CO.,"Software Developers, Applications",APPLICATIONS DEVELOPER,Y,92726.0,2012.0,"COLUMBUS, OHIO",-82.998794,39.961176
9,2927315,CERTIFIED,"IRONBRIDGE CONSULTING, LLC","Information Security Analysts, Web Developers,...",SOFTWARE ENGINEER/ NETWORK ANALYST,Y,57866.0,2011.0,"ARLINGTON, VIRGINIA",-77.106770,38.879970
10,1696111,CERTIFIED,"AXON SOLUTIONS, INC.",Computer Systems Analysts,MANAGING CONSULTANT,Y,91998.0,2014.0,"UNIVERSAL CITY, CALIFORNIA",-118.350578,34.139769
11,2042418,CERTIFIED,MICROSOFT CORPORATION,"Software Developers, Applications",SOFTWARE DEVELOPMENT ENGINEER IN TEST,Y,86278.0,2013.0,"REDMOND, WASHINGTON",-122.121512,47.673988
12,2556938,CERTIFIED,MOBILE IRON INC.,"Software Developers, Systems Software",SYSTEMS ENGINEER,Y,103709.0,2012.0,"MOUNTAIN VIEW, CALIFORNIA",-122.083851,37.386052
13,1620167,CERTIFIED,"TECHNIP USA, INC.",Chemical Engineers,FACILITIES SPECIALIST,Y,75298.0,2014.0,"HOUSTON, TEXAS",-95.369803,29.760427
14,2066155,CERTIFIED,"COMMVAULT AMERICAS, INC.",Computer Systems Analysts,SYSTEM TESTER,Y,74651.0,2013.0,"OCEANPORT, NEW JERSEY",-74.015138,40.318166
15,2836033,CERTIFIED,CUMMINS INC.,Mechanical Engineers,SENIOR MECHANICAL ENGINEER - PERFORMANCE IMPRO...,Y,66019.0,2011.0,"FRIDLEY, MINNESOTA",-93.263282,45.086077
16,1649897,CERTIFIED,"PACIFIC INVESTMENT MANAGEMENT COMPANY, LLC","Securities, Commodities, and Financial Service...","VICE PRESIDENT, PORTFOLIO MANAGER",Y,57949.0,2014.0,"NEWPORT BEACH, CALIFORNIA",-117.928947,33.618910
17,734416,CERTIFIED,UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER AT S...,"HEALTH SPECIALTIES TEACHERS, POSTSECONDARY",ASSISTANT PROFESSOR,Y,96277.0,2015.0,"SAN ANTONIO, TEXAS",-98.493628,29.424122
18,2959714,CERTIFIED,"HARTE-HANKS DATA TECHNOLOGIES, INC.",Marketing Managers,ASSOCIATE PRODUCT MANAGER,Y,55931.0,2011.0,"LINTHICUM HEIGHTS, MARYLAND",-76.652746,39.205108
19,1498142,CERTIFIED,LENORA SYSTEMS INC,Computer Systems Analysts,PROGRAMMER ANALYST,Y,57075.0,2014.0,"DALLAS, TEXAS",-96.796988,32.776664
20,98397,CERTIFIED,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,TECHNOLOGY LEAD - US,Y,89149.0,2016.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
21,2196173,CERTIFIED,HITACHI CONSULTING CORPORATION,"Software Developers, Applications",SOFTWARE ENGINEER,Y,73174.0,2013.0,"REDMOND, WASHINGTON",-122.121512,47.673988
22,2511101,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,PROJECT LEAD,Y,76315.0,2012.0,"TAMPA, FLORIDA",-82.457178,27.950575
24,718222,CERTIFIED,"FORTINET, INC.","COMPUTER OCCUPATIONS, ALL OTHER",CARRIER READINESS TEST ENGINEER,Y,77563.0,2015.0,"SUNNYVALE, CALIFORNIA",-122.036350,37.368830
25,46751,CERTIFIED,"INDEED, INC.",MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,ONLINE MARKET ANALYST,N,60258.0,2016.0,"AUSTIN, TEXAS",-97.743061,30.267153
26,1961506,CERTIFIED,"CAZARCH, INC.",Architectural and Civil Drafters,ARCHITETURAL DESIGNER,Y,40685.0,2013.0,"BROOKLYN, NEW YORK",-73.944158,40.678178
27,1862817,CERTIFIED,CREDIT SUISSE SECURITIES (USA) LLC,Accountants and Auditors,EXEMPT NON-OFFICER,Y,55370.0,2013.0,"NEW YORK, NEW YORK",-74.005941,40.712784
28,2723040,CERTIFIED,"JCG TECHNOLOGIES, INC.",Computer Programmers,COMPUTER PROGRAMMER,Y,67995.0,2011.0,"WESTBOROUGH, MASSACHUSETTS",-71.616129,42.269522
29,913307,DENIED,APERI CORPORATION,COMPUTER HARDWARE ENGINEERS,SYSTEMS ENGINEER,Y,66200.0,2015.0,"CAMARILLO, CALIFORNIA",-119.037602,34.216394
30,2472137,CERTIFIED,"UPMC EMERGENCY MEDICINE, INC.","Physicians and Surgeons, All Other",HOSPITALIST,Y,81994.0,2012.0,"GREENVILLE, PENNSYLVANIA",-80.391179,41.404499
31,1773253,CERTIFIED,DELOITTE CONSULTING LLP,Computer Systems Analysts,CONSULTANT,Y,75899.0,2014.0,"BALA CYNWYD, PENNSYLVANIA",-75.230404,40.013142
...,...,...,...,...,...,...,...,...,...,...,...
450745,1322273,CERTIFIED,TEKSYSTEMS GLOBAL SERVICES LLC,"Software Developers, Applications",SENIOR HYPERION CONSULTANT,Y,98675.0,2014.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
450746,1181903,CERTIFIED,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYSTS,CONSULTANT - US,Y,71906.0,2015.0,"FORT WORTH, TEXAS",-97.330766,32.755488
450747,1688051,CERTIFIED,TEKWISSEN LLC,Computer Systems Analysts,SR. PROGRAMMER ANALYST,Y,75046.0,2014.0,"SAN BRUNO, CALIFORNIA",-122.411083,37.630490
450748,2919320,CERTIFIED,YIPIT INC.,Computer Systems Analysts,SOFTWARE SYSTEMS ANALYST,Y,74222.0,2011.0,"NEW YORK, NEW YORK",-74.005941,40.712784
450749,818213,CERTIFIED,"GRANDISON MANAGEMENT, INC.",PHYSICAL THERAPISTS,PHYSICAL THERAPIST,Y,55036.8,2015.0,"ORCHARD PARK, NEW YORK",-78.743919,42.767559
450750,2538867,CERTIFIED,INFOSYS LIMITED,Computer Systems Analysts,TECHNOLOGY LEAD - US,Y,67122.0,2012.0,"DALLAS, TEXAS",-96.796988,32.776664
450751,537692,CERTIFIED,"ALCATEL-LUCENT USA, INC. (DBA NOKIA)",ELECTRICAL ENGINEERS,SENIOR SYSTEM TEST ENGINEER,Y,108160.0,2016.0,"MURRAY HILL, NEW JERSEY",-74.401265,40.695141
450753,2854897,CERTIFIED,UNIVERSITY OF WASHINGTON,"Business Teachers, Postsecondary",ASSISTANT PROFESSOR,Y,33050.0,2011.0,"BOTHELL, WASHINGTON",-122.205588,47.760950
450754,190542,CERTIFIED,"WAL-MART ASSOCIATES, INC.",COMPUTER SYSTEMS ANALYSTS,SYSTEMS ANALYST,Y,79331.0,2016.0,"BENTONVILLE, ARKANSAS",-94.208817,36.372854
450755,268450,CERTIFIED,SOFTWARE TRANSFORMATIONS INC,COMPUTER PROGRAMMERS,COMPUTER PROGRAMMER,N,45011.0,2016.0,"PLANO, TEXAS",-96.698886,33.019843
450756,2215026,CERTIFIED,DELOITTE CONSULTING LLP,Financial Analysts,MANAGER,Y,74859.0,2013.0,"BUFFALO, NEW YORK",-78.878369,42.886447
450757,313397,CERTIFIED,FATPIPE TECHNOLOGIES,"SOFTWARE DEVELOPERS, APPLICATIONS",PROGRAMMER ANALYST,N,60112.0,2016.0,"SALT LAKE CITY, UTAH",-111.891047,40.760779
450758,786420,CERTIFIED,IBM INDIA PRIVATE LIMITED,COMPUTER PROGRAMMERS,TEST SPECIALIST,Y,70304.0,2015.0,"PISCATAWAY, NEW JERSEY",-74.464286,40.554887
450760,1357308,CERTIFIED,DELOITTE TAX LLP,Accountants and Auditors,TAX CONSULTANT II,Y,43243.0,2014.0,"OMAHA, NEBRASKA",-95.997988,41.252363
450761,2289363,CERTIFIED,"HCL AMERICA, INC.",Computer Systems Analysts,SYSTEMS ANALYST,Y,65021.0,2012.0,"BELLEVUE, WASHINGTON",-122.201516,47.610150
450762,351102,CERTIFIED,REVA ENTERPRISES LLC,"SOFTWARE DEVELOPERS, APPLICATIONS",SOFTWARE DEVELOPER,N,65811.0,2016.0,"FARMINGTON HILLS, MICHIGAN",-83.367717,42.498994
450763,124861,CERTIFIED,INFOSYS LIMITED,COMPUTER SYSTEMS ANALYST,ASSOCIATE CONSULTANT - US,N,61173.0,2016.0,"CHARLOTTE, NORTH CAROLINA",-80.843127,35.227087
450764,287792,CERTIFIED,"INTELLIPRO GROUP, INC.","SOFTWARE DEVELOPERS, APPLICATIONS",SOFTWARE DEVELOPER,Y,98342.0,2016.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
450765,794796,CERTIFIED,"NEELINFO, INC.",MANAGEMENT ANALYSTS,BUSINESS ANALYST,Y,63024.0,2015.0,"SANTA CLARA, CALIFORNIA",-121.955236,37.354108
450766,2601674,CERTIFIED,CARNEGIE MELLON UNIVERSITY,Computer and Information Research Scientists,PROJECT SCIENTIST,Y,47819.0,2012.0,"ALBUQUERQUE, NEW MEXICO",-106.605553,35.085334
450767,1488240,CERTIFIED,PAMPA INDEPENDENT SCHOOL DISTRICT,"Elementary School Teachers, Except Special Edu...",ELEMENTARY SCHOOL BILINGUAL TEACHER,Y,36320.0,2014.0,"PAMPA, TEXAS",NaN,NaN
450768,1048617,CERTIFIED,"QUALCOMM TECHNOLOGIES, INC.","SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",STAFF SOFTWARE/SYSTEMS TEST ENGINEER,Y,113589.0,2015.0,"SAN DIEGO, CALIFORNIA",-117.161084,32.715738
450769,880755,CERTIFIED,"MEDITERRANEAN SHIPPING COMPANY (USA), INC.",MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,BUSINESS DEVELOPMENT ANALYST,Y,31158.0,2015.0,"MT. PLEASANT, SOUTH CAROLINA",-79.828426,32.832322
450770,1749805,CERTIFIED,"JOHNSON CONTROLS, INC.",Computer and Information Systems Managers,DIRECTOR IT ARCHITECTURE AND APPLICATION DELIVERY,Y,113526.0,2014.0,"MILWAUKEE, WISCONSIN",-87.906474,43.038902
450771,771675,CERTIFIED,ST. JOSEPH HEALTH SYSTEM,"INTERNISTS, GENERAL",PHYSICIAN (INTERNAL MEDICINE),Y,45552.0,2015.0,"TAWAS CITY, MICHIGAN",NaN,NaN
450772,1922553,CERTIFIED,SRT IT CORPORATION,Computer Systems Analysts,SYSTEMS ANALYST,Y,58718.0,2013.0,"BIRMINGHAM, ALABAMA",-86.802490,33.520661
450773,273396,CERTIFIED,IBM INDIA PRIVATE LIMITED,COMPUTER PROGRAMMERS,APPLICATION PROGRAMMER,Y,74277.0,2016.0,"LUTHERVILLE TIMONIUM, MARYLAND",NaN,NaN
450774,1596482,CERTIFIED,UNIVERSAL SOFTWARE CORPORATION,Computer Programmers,PROGRAMMER ANALYST,Y,45282.0,2014.0,"ADDISON, TEXAS",-96.829169,32.961790
450775,538027,CERTIFIED,DEMATIC CORPORATION,ELECTRICAL ENGINEERS,CONTROLS SYSTEM ENGINEER 1,N,56056.0,2016.0,"GRAND RAPIDS, MICHIGAN",-85.668086,42.963360
450776,1407114,CERTIFIED,SOLUTION IT,Computer Programmers,ORACLE E-BUSINESS SUITE APPLICATIONS TECHNICAL...,Y,86590.0,2014.0,"WOBURN, MASSACHUSETTS",-71.152276,42.479262